CREATE TABLE IF NOT EXISTS flights (
      id TEXT,
      duration TEXT,
      quality TEXT,
      flyTo TEXT,
      conversion TEXT,
      deep_link TEXT,
      airlines TEXT,
      fly_duration TEXT,
      aTimeUTC TEXT,
      has_airport_change TEXT,
      price TEXT,
      bags_price TEXT,
      flyFrom TEXT,
      dTimeUTC TEXT,
      dTime TEXT,
      booking_token TEXT,
      facilitated_booking_available TEXT,
      aTime TEXT,
      distance TEXT,
      fare_basis TEXT,
      flight_no TEXT,
      last_seen TEXT
 );
